[1mdiff --git a/.gitignore b/.gitignore[m
[1mdeleted file mode 100644[m
[1mindex 830fbc8..0000000[m
[1m--- a/.gitignore[m
[1m+++ /dev/null[m
[36m@@ -1,2 +0,0 @@[m
[31m-.DS_Score[m
[31m-log/[m
\ No newline at end of file[m
[1mdiff --git a/hipster.txt b/hipster.txt[m
[1mnew file mode 100644[m
[1mindex 0000000..c05daf9[m
[1m--- /dev/null[m
[1m+++ b/hipster.txt[m
[36m@@ -0,0 +1,4 @@[m
[32m+[m[32mumeric irony cliche, 3 wolf moon paleo plaid tilde. Migas sriracha seitan, gluten-free unicorn cronut activated charcoal narwhal. Tbh semiotics tacos occupy pinterest sustainable activated charcoal typewriter lo-fi heirloom disrupt poutine chia. Stumptown vaporware cred keffiyeh kombucha skateboard health goth migas heirloom scenester. Palo santo gastropub direct trade flannel tumblr, snackwave blog ugh flexitarian fam vape pickled shaman twee organic.[m[41m[m
[32m+[m[32mPitchfork hexagon readymade fam food truck yr swag pabst artisan tofu semiotics irony mlkshk. Adaptogen unicorn iceland, glossier paleo umami bespoke synth hoodie deep v sustainable humblebrag bushwick mlkshk sriracha. Heirloom poke food truck wolf locavore, blog schlitz typewriter coloring book vexillologist stumptown lyft craft beer la croix mixtape. Kitsch plaid offal, kogi raclette chicharrones jianbing ugh +1 keffiyeh jean shorts. Hella roof party celiac pork belly swag. Succulents chillwave blue bottle man braid small batch crucifix chia adaptogen sartorial prism salvia XOXO cliche semiotics chicharrones. Drinking vinegar banh mi tousled church-key pitchfork mixtape listicle shaman vaporware butcher succulents plaid.[m[41m[m
[32m+[m[32mKinfolk organic hammock, distillery DIY single-origin coffee wayfarers farm-to-table selfies plaid woke wolf seitan portland small batch. Snackwave whatever tumeric, kinfolk readymade typewriter farm-to-table portland deep v swag tumblr. Bespoke venmo tousled before they sold out, synth listicle jean shorts cornhole keffiyeh shabby chic tumeric. Tumblr pinterest 90's tote bag hexagon whatever williamsburg yr jean shorts +1 YOLO echo park activated charcoal cornhole banh mi. Crucifix meggings enamel pin small batch chillwave.[m[41m[m
[32m+[m[32mKinfolk organic hammock, distillery DIY single-origin coffee wayfarers farm-to-table selfies plaid woke wolf seitan portland small batch. Snackwave whatever tumeric, kinfolk readymade typewriter farm-to-table portland deep v swag tumblr. Bespoke venmo tousled before they sold out, synth listicle jean shorts cornhole keffiyeh shabby chic tumeric. Tumblr pinterest 90's tote bag hexagon whatever williamsburg yr jean shorts +1 YOLO echo park activated charcoal cornhole banh mi. Crucifix meggings enamel pin small batch chillwave.[m
\ No newline at end of file[m
[1mdiff --git a/level1/level2/level2.txt b/level1/level2/level2.txt[m
[1mnew file mode 100644[m
[1mindex 0000000..d6d2f68[m
[1m--- /dev/null[m
[1m+++ b/level1/level2/level2.txt[m
[36m@@ -0,0 +1,5 @@[m
[32m+[m[32mI'm baby photo booth marfa sustainable master cleanse schlitz. Shaman tbh chicharrones truffaut blog distillery pabst affogato poutine. Activated charcoal VHS hashtag etsy you probably haven't heard of them. Hot chicken tumeric live-edge forage twee woke ethical art party tattooed hoodie fixie banh mi edison bulb tumblr activated charcoal.[m[41m[m
[32m+[m[41m[m
[32m+[m[32mSemiotics lomo occupy, deep v adaptogen put a bird on it taxidermy iceland hella selvage heirloom. Listicle health goth chambray letterpress man bun affogato heirloom thundercats chia fanny pack live-edge aesthetic gastropub shabby chic. Occupy four dollar toast lo-fi, leggings cloud bread cornhole taiyaki next level messenger bag neutra. Truffaut bushwick keytar, fashion axe live-edge hell of quinoa lomo poke bespoke meh vegan 90's. Microdosing woke post-ironic raw denim snackwave farm-to-table, wolf blue bottle sartorial tilde. Banjo chambray man braid cray kitsch bicycle rights brooklyn ethical meggings.[m[41m[m
[32m+[m[41m[m
[32m+[m[32mBeard banh mi tofu, organic direct trade freegan shoreditch aesthetic leggings pour-over tbh selfies. Cronut migas twee fashion axe snackwave 3 wolf moon vape mumblecore polaroid brunch. Trust fund cloud bread polaroid roof party truffaut man bun palo santo meditation synth iPhone gluten-free kickstarter williamsburg distillery. Food truck asymmetrical normcore, cardigan raw denim selvage readymade vape. Cray coloring book blue bottle kinfolk, gentrify migas ramps art party food truck schlitz jean shorts truffaut hella. Neutra skateboard master cleanse tousled, hoodie selvage hashtag tote bag cray +1 direct trade ethical cold-pressed prism.[m
\ No newline at end of file[m
[1mdiff --git a/level1/level2/level3/level3.txt b/level1/level2/level3/level3.txt[m
[1mnew file mode 100644[m
[1mindex 0000000..d3fed75[m
[1m--- /dev/null[m
[1m+++ b/level1/level2/level3/level3.txt[m
[36m@@ -0,0 +1,7 @@[m
[32m+[m[32mSalvia thundercats jianbing lomo 8-bit flexitarian, meh pop-up semiotics trust fund humblebrag cardigan viral typewriter. Edison bulb everyday carry marfa tousled, palo santo wayfarers gentrify wolf knausgaard listicle fanny pack pug. Hot chicken lo-fi ethical brunch, blog marfa hoodie truffaut 3 wolf moon deep v messenger bag shoreditch vice keytar. Flexitarian taxidermy chartreuse bushwick blue bottle dreamcatcher, woke poutine gluten-free raclette cornhole ramps portland 3 wolf moon fashion axe.[m[41m[m
[32m+[m[41m[m
[32m+[m[32mMarfa fingerstache deep v crucifix. Lyft food truck man braid, echo park chia biodiesel neutra four dollar toast four loko godard ethical. Banjo bespoke tattooed kinfolk waistcoat lumbersexual kickstarter yuccie food truck. Cardigan occupy pork belly cray, prism ethical lomo literally enamel pin stumptown knausgaard 90's whatever. Slow-carb post-ironic shabby chic, poke chambray pork belly church-key pickled authentic williamsburg hammock enamel pin. Cronut before they sold out banh mi, leggings pork belly gentrify chillwave green juice butcher lumbersexual paleo activated charcoal tilde.[m[41m[m
[32m+[m[41m[m
[32m+[m[32mBushwick poutine blue bottle typewriter, biodiesel roof party intelligentsia master cleanse lomo photo booth. Vice pitchfork vexillologist pinterest meditation, XOXO tote bag. Biodiesel meditation cornhole activated charcoal meggings bitters thundercats pug. Adaptogen la croix glossier, chambray listicle tumeric copper mug. Forage affogato raw denim blue bottle. Slow-carb leggings offal swag af hexagon lo-fi asymmetrical beard banjo paleo snackwave yuccie etsy tousled.[m[41m[m
[32m+[m[41m[m
[32m+[m[32mKinfolk gentrify banjo, neutra viral sartorial kitsch. Everyday carry narwhal neutra, microdosing mumblecore celiac 8-bit. Gentrify sriracha yuccie jianbing vegan pour-over. Fam fanny pack irony pour-over pabst cloud bread disrupt brunch typewriter mumblecore gochujang art party. Fashion axe actually bespoke mustache. Literally prism hella keffiyeh seitan selvage four loko. Kinfolk whatever bespoke, semiotics tumblr flexitarian actually lo-fi before they sold out snackwave cray pabst banh mi jean shorts taxidermy.[m
\ No newline at end of file[m
[1mdiff --git a/newfile.txt b/newfile.txt[m
[1mnew file mode 100644[m
[1mindex 0000000..86af7f2[m
[1m--- /dev/null[m
[1m+++ b/newfile.txt[m
[36m@@ -0,0 +1 @@[m
[32m+[m[32mjust a test of ls-files[m
\ No newline at end of file[m
